import type { AchievementDef } from '../types'

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'first_habit',
    title: 'Primeiro Passo',
    description: 'Complete seu primeiro hábito',
    emoji: '🌱',
    gradient: 'from-emerald-400 to-teal-500',
    points: 10,
    condition: (s) => s.totalHabitsCompleted >= 1,
  },
  {
    id: 'streak_3',
    title: 'Três é Pouco',
    description: '3 dias seguidos completando hábitos',
    emoji: '🔥',
    gradient: 'from-orange-400 to-red-500',
    points: 25,
    condition: (s) => s.currentStreak >= 3,
  },
  {
    id: 'streak_7',
    title: 'Week Warrior',
    description: '7 dias seguidos — você é imparável!',
    emoji: '⚡',
    gradient: 'from-yellow-400 to-orange-500',
    points: 75,
    condition: (s) => s.currentStreak >= 7,
  },
  {
    id: 'streak_30',
    title: 'Mês Épico',
    description: '30 dias seguidos. Lenda!',
    emoji: '👑',
    gradient: 'from-violet-500 to-fuchsia-600',
    points: 300,
    condition: (s) => s.currentStreak >= 30,
  },
  {
    id: 'streak_100',
    title: 'Centenário',
    description: '100 dias seguidos. Você é uma máquina!',
    emoji: '💎',
    gradient: 'from-sky-400 to-violet-600',
    points: 1000,
    condition: (s) => s.currentStreak >= 100,
  },
  {
    id: 'habits_5',
    title: 'Colecionador',
    description: 'Crie 5 hábitos diferentes',
    emoji: '🎯',
    gradient: 'from-pink-400 to-rose-500',
    points: 30,
    condition: (s) => s.habitsCount >= 5,
  },
  {
    id: 'habits_50',
    title: 'Cinquentão',
    description: '50 completions de hábitos no total',
    emoji: '🏆',
    gradient: 'from-amber-400 to-yellow-500',
    points: 100,
    condition: (s) => s.totalHabitsCompleted >= 50,
  },
  {
    id: 'habits_200',
    title: 'Duzentos!',
    description: '200 completions de hábitos no total',
    emoji: '🚀',
    gradient: 'from-violet-400 to-sky-500',
    points: 300,
    condition: (s) => s.totalHabitsCompleted >= 200,
  },
  {
    id: 'journal_first',
    title: 'Escritor Iniciante',
    description: 'Escreva sua primeira entrada no diário',
    emoji: '✍️',
    gradient: 'from-fuchsia-400 to-pink-500',
    points: 15,
    condition: (s) => s.totalJournalEntries >= 1,
  },
  {
    id: 'journal_7',
    title: 'Diário da Semana',
    description: '7 entradas no diário',
    emoji: '📔',
    gradient: 'from-emerald-400 to-sky-500',
    points: 50,
    condition: (s) => s.totalJournalEntries >= 7,
  },
  {
    id: 'journal_30',
    title: 'Cronista',
    description: '30 entradas no diário',
    emoji: '📚',
    gradient: 'from-violet-500 to-pink-500',
    points: 150,
    condition: (s) => s.totalJournalEntries >= 30,
  },
  {
    id: 'points_100',
    title: 'Centenário de Pontos',
    description: 'Alcance 100 pontos',
    emoji: '💯',
    gradient: 'from-teal-400 to-emerald-500',
    points: 0,
    condition: (s) => s.totalPoints >= 100,
  },
  {
    id: 'longest_streak_14',
    title: 'Duas Semanas',
    description: 'Maior streak de 14 dias',
    emoji: '🌟',
    gradient: 'from-amber-300 to-fuchsia-500',
    points: 150,
    condition: (s) => s.longestStreak >= 14,
  },

  // ── Social achievements ──────────────────────────────────────────
  {
    id: 'first_friend',
    title: 'Primeiro Amigo',
    description: 'Conecte-se com seu primeiro amigo',
    emoji: '🤝',
    gradient: 'from-sky-400 to-violet-500',
    points: 20,
    condition: (s) => s.friendsCount >= 1,
  },
  {
    id: 'sync_first',
    title: 'Sincronizados',
    description: 'Ambos fizeram o mesmo hábito no mesmo dia pela primeira vez',
    emoji: '🫂',
    gradient: 'from-violet-500 to-fuchsia-500',
    points: 30,
    condition: (s) => s.partnerBonusCount >= 1,
  },
  {
    id: 'sync_5',
    title: 'Dupla Dinâmica',
    description: '5 vezes que vocês dois fizeram juntos',
    emoji: '🔥',
    gradient: 'from-fuchsia-500 to-pink-500',
    points: 75,
    condition: (s) => s.partnerBonusCount >= 5,
  },
  {
    id: 'sync_30',
    title: 'Parceiros Inseparáveis',
    description: '30 dias fazendo hábitos juntos',
    emoji: '💫',
    gradient: 'from-violet-600 to-sky-500',
    points: 250,
    condition: (s) => s.partnerBonusCount >= 30,
  },
]
